#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
PY="${PYTHON:-python}"
# PeMS04 | Vanilla $(\Ainit, T{=}1)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=none epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 seed=$SEED; done
# PeMS04 | Frozen-$\phi$ $(\Ainit, T{=}10)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true seed=$SEED; done
# PeMS04 | Distilled $(A_{\phi^*}, T{=}1)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=none epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 ++adj_load=learned_graphs/pems04_bilevel_seed42.npy seed=$SEED; done
# PeMS04 | Recombined $(A_{\phi^*}, T{=}10)$, seed 42
"$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems04_bilevel_seed42.npy seed=42
# PeMS04 | Recombined $(A_{\phi^*}, T{=}10)$, seed 123
"$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems04_bilevel_seed123.npy seed=123
# PeMS04 | Recombined $(A_{\phi^*}, T{=}10)$, seed 456
"$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems04_bilevel_seed456.npy seed=456
# PeMS04 | Recombined $(A_{\phi^*}, T{=}10)$, seed 789
"$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems04_bilevel_seed789.npy seed=789
# PeMS04 | Recombined $(A_{\phi^*}, T{=}10)$, seed 1024
"$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems04_bilevel_seed1024.npy seed=1024
# PeMS04 | Bilevel
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems04 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 seed=$SEED; done
# PeMS07 | Vanilla $(\Ainit, T{=}1)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=none epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 seed=$SEED; done
# PeMS07 | Frozen-$\phi$ $(\Ainit, T{=}10)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true seed=$SEED; done
# PeMS07 | Distilled $(A_{\phi^*}, T{=}1)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=none epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 ++adj_load=learned_graphs/pems07_bilevel_seed42.npy seed=$SEED; done
# PeMS07 | Recombined $(A_{\phi^*}, T{=}10)$, seed 42
"$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems07_bilevel_seed42.npy seed=42
# PeMS07 | Recombined $(A_{\phi^*}, T{=}10)$, seed 123
"$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems07_bilevel_seed123.npy seed=123
# PeMS07 | Recombined $(A_{\phi^*}, T{=}10)$, seed 456
"$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems07_bilevel_seed456.npy seed=456
# PeMS07 | Recombined $(A_{\phi^*}, T{=}10)$, seed 789
"$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems07_bilevel_seed789.npy seed=789
# PeMS07 | Recombined $(A_{\phi^*}, T{=}10)$, seed 1024
"$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems07_bilevel_seed1024.npy seed=1024
# PeMS07 | Bilevel
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems07 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 seed=$SEED; done
# PeMS08 | Vanilla $(\Ainit, T{=}1)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=none epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 seed=$SEED; done
# PeMS08 | Frozen-$\phi$ $(\Ainit, T{=}10)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true seed=$SEED; done
# PeMS08 | Distilled $(A_{\phi^*}, T{=}1)$
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=none epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 ++adj_load=learned_graphs/pems08_bilevel_seed42.npy seed=$SEED; done
# PeMS08 | Recombined $(A_{\phi^*}, T{=}10)$, seed 42
"$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems08_bilevel_seed42.npy seed=42
# PeMS08 | Recombined $(A_{\phi^*}, T{=}10)$, seed 123
"$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems08_bilevel_seed123.npy seed=123
# PeMS08 | Recombined $(A_{\phi^*}, T{=}10)$, seed 456
"$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems08_bilevel_seed456.npy seed=456
# PeMS08 | Recombined $(A_{\phi^*}, T{=}10)$, seed 789
"$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems08_bilevel_seed789.npy seed=789
# PeMS08 | Recombined $(A_{\phi^*}, T{=}10)$, seed 1024
"$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 rewiring.freeze_phi=true ++adj_load=learned_graphs/pems08_bilevel_seed1024.npy seed=1024
# PeMS08 | Bilevel
for SEED in 42 123 456 789 1024; do "$PY" experiments/run_realworld_rewired.py dataset=pems08 model=mptcn_diff rewiring=bilevel epochs=100 patience=30 lr_scheduler.hparams.T_max=100 model.mode=tas model.hparams.hidden_size=64 model.hparams.n_layers=2 model.hparams.tcn_layers=3 model.min_tcn_layers=3 rewiring.policy_type=relative_reweight rewiring.outer_lr=0.001 rewiring.inner_steps=10 seed=$SEED; done
